name: CD Pipeline

on:
  workflow_run:
    workflows: ["Docker Image CI"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull armanloonix/credit-sea:latest
    - name: Delete Old docker container
      run: sudo docker rm -f credit-sea-container || true
    - name: Run Docker Container
      run: sudo docker run -d \
          -e MONGO_URI="***" \
          -p 5000:5000 \
          --name credit-sea-container \
          armanloonix/credit-sea
